name: Terraform Deployment

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show OIDC Claims
        uses: actions/github-script@v7
        with:
          script: |
            const id_token = await core.getIDToken("sts.amazonaws.com");
            const payload = JSON.parse(
              Buffer.from(id_token.split('.')[1], 'base64').toString()
            );
            console.log(JSON.stringify(payload, null, 2));

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.ROLE_NAME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      # PR Checks Only
      - name: Terraform Format Check
        if: github.event_name == 'pull_request'
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        if: github.event_name == 'pull_request'
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color

      # Apply Only After Merge to Main
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
